[tool.poetry]
name = "ciconia"
version = "0.1.0"
description = "Repository for python, debian and other packages with one REST API to rule them all."
authors = ["Igor Ovsyannikov <kamish@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.2"
django-environ = "^0.4.5"
django-crispy-forms = "^1.7"

[tool.poetry.dev-dependencies]
pylint = "^2.3"
pytest = "^4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
