# Generated by Django 2.2.1 on 2019-05-14 17:23

import anchor.packages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pkg_type",
                    models.CharField(
                        choices=[
                            (anchor.packages.models.PackageTypes("python"), "python"),
                            (anchor.packages.models.PackageTypes("rpm"), "rpm"),
                            (anchor.packages.models.PackageTypes("deb"), "deb"),
                            (anchor.packages.models.PackageTypes("docker"), "docker"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=64)),
                (
                    "version",
                    models.CharField(max_length=16, verbose_name="Latest version"),
                ),
                ("summary", models.TextField(null=True)),
                ("updated", models.DateTimeField(verbose_name="Last updated")),
                (
                    "info",
                    models.TextField(null=True, verbose_name="Package information"),
                ),
            ],
        )
    ]
