# Generated by Django 2.2.1 on 2019-05-18 05:18

import anchor.packages.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pkg_type",
                    models.CharField(
                        choices=[
                            (anchor.packages.models.PackageTypes("python"), "python"),
                            (anchor.packages.models.PackageTypes("rpm"), "rpm"),
                            (anchor.packages.models.PackageTypes("deb"), "deb"),
                            (anchor.packages.models.PackageTypes("docker"), "docker"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=64)),
                (
                    "version",
                    models.CharField(max_length=64, verbose_name="Latest version"),
                ),
                ("summary", models.TextField(null=True)),
                ("updated", models.DateTimeField(verbose_name="Last updated")),
                (
                    "description",
                    models.TextField(null=True, verbose_name="Description"),
                ),
            ],
            options={"unique_together": {("pkg_type", "name")}},
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_criteria",
                    models.TextField(verbose_name="Retention settings (JSON)"),
                ),
                (
                    "applied_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packages.Package",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackageFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=64, unique=True)),
                ("fileobj", models.FileField(upload_to="")),
                ("size", models.IntegerField()),
                ("version", models.CharField(max_length=64)),
                ("uploaded", models.DateTimeField()),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packages.Package",
                    ),
                ),
            ],
        ),
    ]
