# Generated by Django 2.2.2 on 2019-06-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("packages", "0003_auto_20190616_0910")]

    operations = [migrations.RemoveField(model_name="packagefile", name="owner")]
