# Generated by Django 2.2.2 on 2019-06-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_grouprole_role_userrole"),
        ("packages", "0004_remove_packagefile_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="roles",
            field=models.ManyToManyField(related_name="roles", to="users.Role"),
        )
    ]
