# Generated by Django 2.2.2 on 2019-06-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_grouprole_role_userrole"),
        ("packages", "0005_package_roles"),
    ]

    operations = [
        migrations.RemoveField(model_name="package", name="roles"),
        migrations.AddField(
            model_name="package",
            name="group_roles",
            field=models.ManyToManyField(to="users.GroupRole"),
        ),
        migrations.AddField(
            model_name="package",
            name="user_roles",
            field=models.ManyToManyField(to="users.UserRole"),
        ),
    ]
