# Generated by Django 2.2.2 on 2019-06-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("packages", "0006_auto_20190618_1027")]

    operations = [
        migrations.RemoveField(model_name="package", name="description"),
        migrations.AddField(
            model_name="package", name="_attrs", field=models.TextField(default="{}")
        ),
    ]
