# Generated by Django 2.2.1 on 2019-05-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("pypi", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="packagefile", old_name="pkg_type", new_name="dist_type"
        )
    ]
