# Generated by Django 2.2 on 2019-05-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pypi", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="packagefile",
            name="filename",
            field=models.CharField(max_length=64, unique=True),
        )
    ]
