# Generated by Django 2.2 on 2019-04-22 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('version', models.CharField(max_length=16, verbose_name='Latest version')),
                ('updated', models.DateTimeField(verbose_name='Last updated')),
                ('info', models.TextField(verbose_name='Package information')),
            ],
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32)),
                ('info', models.TextField(verbose_name='Package information')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pypi.PythonPackage')),
            ],
        ),
        migrations.CreateModel(
            name='PackageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File itself', models.FileField(upload_to='pypi')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pypi.PackageVersion')),
            ],
        ),
    ]
