# Generated by Django 2.2 on 2019-05-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pypi", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="pythonpackage",
            name="summary",
            field=models.TextField(null=True),
        )
    ]
