# Generated by Django 2.2 on 2019-05-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pypi", "0002_pythonpackage_summary")]

    operations = [
        migrations.AlterField(
            model_name="packagefile",
            name="sha256",
            field=models.CharField(max_length=64, unique=True),
        )
    ]
