# Generated by Django 2.2 on 2019-05-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("pypi", "0002_auto_20190505_1509")]

    operations = [
        migrations.RenameModel(old_name="PythonPackage", new_name="Project"),
        migrations.RenameField(
            model_name="packagefile", old_name="package", new_name="project"
        ),
    ]
